export const INVESTORS_COPY = {
  pt: {
    heroKicker: 'Quem somos',
    heroTitle: 'Quem está por trás da Ummix',
    heroDescription: 'A Ummix é construída por pessoas que combinam experiência em mídia, tecnologia e operação. Conheça quem coloca essa visão em movimento todos os dias.',
    leadershipKicker: 'As pessoas por trás da Ummix',
    leadershipTitle: 'Sócios e lideranças',
    leadershipDescription: 'Uma equipe que combina visão de negócio, tecnologia, dados e execução.',
    leadershipAriaLabel: 'Sócios e lideranças da Ummix',
    leadershipRoles: ['Sócio e liderança', 'Sócia e liderança', 'Sócio e liderança', 'Sócio e liderança', 'Sócia-investidora'],
    ecosystemKicker: 'Ecossistema Ummix',
    ecosystemTitle: 'Pessoas e empresas que constroem a Ummix.',
    ecosystemDescription: 'A Ummix cresce conectada a um ecossistema de empresas que compartilham visão de longo prazo, conhecimento e capacidade de execução.',
    velloreAriaLabel: 'Vellore Ventures',
    velloreKicker: 'Grupo Vellore',
    velloreTitle: 'Um grupo que reúne negócios e visão de futuro.',
    velloreDescription: 'A Vellore Ventures participa da construção da Ummix e conecta a empresa a um grupo diverso, formado por negócios que movimentam diferentes mercados.',
    velloreCompaniesAriaLabel: 'Empresas do grupo Vellore',
    workintechKicker: 'WorkinTech',
    workintechTitle: 'Tecnologia que aproxima pessoas, processos e negócios.',
    workintechDescription: 'A WorkinTech faz parte do ecossistema da Ummix e representa a conexão com empresas que usam tecnologia para organizar operações, criar oportunidades e ampliar impacto.',
  },
  en: {
    heroKicker: 'About us',
    heroTitle: 'The people behind Ummix',
    heroDescription: 'Ummix is built by people who combine experience in media, technology and operations. Meet the people who put this vision into motion every day.',
    leadershipKicker: 'The people behind Ummix',
    leadershipTitle: 'Partners and leaders',
    leadershipDescription: 'A team that combines business vision, technology, data and execution.',
    leadershipAriaLabel: 'Ummix partners and leaders',
    leadershipRoles: ['Partner and leader', 'Partner and leader', 'Partner and leader', 'Partner and leader', 'Investor partner'],
    ecosystemKicker: 'Ummix ecosystem',
    ecosystemTitle: 'People and companies building Ummix.',
    ecosystemDescription: 'Ummix grows connected to an ecosystem of companies that share a long-term vision, knowledge and the ability to execute.',
    velloreAriaLabel: 'Vellore Ventures',
    velloreKicker: 'Vellore Group',
    velloreTitle: 'A group bringing together businesses and a forward-looking vision.',
    velloreDescription: 'Vellore Ventures helps build Ummix and connects the company to a diverse group of businesses moving different markets forward.',
    velloreCompaniesAriaLabel: 'Vellore Group companies',
    workintechKicker: 'WorkinTech',
    workintechTitle: 'Technology that brings people, processes and businesses closer.',
    workintechDescription: 'WorkinTech is part of the Ummix ecosystem and represents our connection with companies using technology to organize operations, create opportunities and expand impact.',
  },
  es: {
    heroKicker: 'Quiénes somos',
    heroTitle: 'Quién está detrás de Ummix',
    heroDescription: 'Ummix está construida por personas que combinan experiencia en medios, tecnología y operaciones. Conoce a quienes ponen esta visión en movimiento cada día.',
    leadershipKicker: 'Las personas detrás de Ummix',
    leadershipTitle: 'Socios y líderes',
    leadershipDescription: 'Un equipo que combina visión de negocio, tecnología, datos y ejecución.',
    leadershipAriaLabel: 'Socios y líderes de Ummix',
    leadershipRoles: ['Socio y líder', 'Socia y líder', 'Socio y líder', 'Socio y líder', 'Socia inversora'],
    ecosystemKicker: 'Ecosistema Ummix',
    ecosystemTitle: 'Personas y empresas que construyen Ummix.',
    ecosystemDescription: 'Ummix crece conectada a un ecosistema de empresas que comparten visión a largo plazo, conocimiento y capacidad de ejecución.',
    velloreAriaLabel: 'Vellore Ventures',
    velloreKicker: 'Grupo Vellore',
    velloreTitle: 'Un grupo que reúne negocios y una visión de futuro.',
    velloreDescription: 'Vellore Ventures participa en la construcción de Ummix y conecta la empresa con un grupo diverso, formado por negocios que mueven distintos mercados.',
    velloreCompaniesAriaLabel: 'Empresas del Grupo Vellore',
    workintechKicker: 'WorkinTech',
    workintechTitle: 'Tecnología que acerca personas, procesos y negocios.',
    workintechDescription: 'WorkinTech forma parte del ecosistema de Ummix y representa la conexión con empresas que utilizan la tecnología para organizar operaciones, crear oportunidades y ampliar su impacto.',
  },
}
