export const CASHBACK_COPY = {
  pt: {
    eyebrow: 'Programa de Cashback Ummix Ads',
    heroTitle: 'Anuncie e ganhe',
    heroAccent: 'até 3% de cashback',
    heroDescription: 'A cada contrato fechado, a Ummix Ads devolve parte do valor para quem participou da negociação. Cadastre-se e comece a receber.',
    platformShort: 'Acessar plataforma',
    platformLong: 'Acessar plataforma de cashback',
    howItWorks: 'Como funciona',
    eligibility: 'Elegibilidade',
    eligibilityTitle: 'Quem tem direito ao cashback?',
    eligibilityDescription: 'Cada participante elegível recebe 1% de cashback, totalizando até 3% distribuídos por contrato.',
    participants: [
      ['Contratante', 'O anunciante que realiza a contratação da campanha diretamente.'],
      ['Mídia', 'O veículo que assina o PI, quando aplicável à negociação.'],
      ['Agência / Agência Digital / Gestor de Tráfego', 'Gestor ou intermediador responsável pela contratação.'],
    ],
    eachCashback: '1% de cashback',
    rulesTitle: 'Regras para receber o cashback',
    rules: [
      'O contrato esteja com o pagamento realizado integralmente até a data de vencimento.',
      'O participante possua cadastro ativo na Plataforma de Cashback da Ummix Ads.',
      'Solicite o crédito direto na Plataforma de Cashback da Ummix Ads.',
    ],
    howKicker: 'Como funciona',
    howTitle: 'Do cadastro ao resgate, em cinco passos.',
    howDescription: 'O processo é simples e transparente. Acompanhe cada etapa.',
    stepLabel: 'PASSO',
    steps: [
      ['Cadastro', 'O participante realiza seu cadastro na Plataforma de Cashback da Ummix Ads.'],
      ['Pagamento do contrato', 'Após a confirmação do pagamento dentro do prazo de vencimento, o cashback torna-se elegível.'],
      ['Solicitação', 'O participante solicita o crédito direto na plataforma, informando os dados do contrato.'],
      ['Crédito disponibilizado', 'Após a validação das informações, o valor é creditado na conta do participante dentro da plataforma.'],
      ['Utilização do benefício', 'O crédito pode ser usado para resgatar vouchers, trocar por produtos parceiros ou sacar em dinheiro.'],
    ],
    highlightTitle: 'Até 3% distribuídos por contrato.',
    highlightDescription: 'Contratante, veículo de mídia e agência recebem 1% cada. O cashback é creditado de forma transparente e tem validade de 90 dias após a disponibilização.',
    split: ['Contratante: 1%', 'Veículo: 1%', 'Agência: 1%'],
    ctaTitle: 'Solicitar cashback',
    cta: 'Solicitar meu cashback',
  },
  en: {
    eyebrow: 'Ummix Ads Cashback Program',
    heroTitle: 'Advertise and earn',
    heroAccent: 'up to 3% cashback',
    heroDescription: 'With every contract closed, Ummix Ads returns part of the value to everyone who took part in the negotiation. Sign up and start earning.',
    platformShort: 'Access platform',
    platformLong: 'Access cashback platform',
    howItWorks: 'How it works',
    eligibility: 'Eligibility',
    eligibilityTitle: 'Who is eligible for cashback?',
    eligibilityDescription: 'Each eligible participant receives 1% cashback, for up to 3% distributed per contract.',
    participants: [
      ['Contracting client', 'The advertiser that directly hires the campaign.'],
      ['Media outlet', 'The outlet that signs the PI, when applicable to the negotiation.'],
      ['Agency / Digital Agency / Media Buyer', 'The manager or intermediary responsible for the contract.'],
    ],
    eachCashback: '1% cashback',
    rulesTitle: 'Rules for receiving cashback',
    rules: [
      'The contract must be paid in full by its due date.',
      'The participant must have an active account on the Ummix Ads Cashback Platform.',
      'The credit must be requested directly on the Ummix Ads Cashback Platform.',
    ],
    howKicker: 'How it works',
    howTitle: 'From sign-up to redemption, in five steps.',
    howDescription: 'The process is simple and transparent. Follow every stage.',
    stepLabel: 'STEP',
    steps: [
      ['Sign-up', 'The participant creates an account on the Ummix Ads Cashback Platform.'],
      ['Contract payment', 'After payment is confirmed within the due date, cashback becomes eligible.'],
      ['Request', 'The participant requests the credit on the platform and provides the contract details.'],
      ['Credit available', 'After the information is validated, the amount is credited to the participant account on the platform.'],
      ['Use the benefit', 'The credit can be used to redeem vouchers, exchange for partner products or withdraw cash.'],
    ],
    highlightTitle: 'Up to 3% distributed per contract.',
    highlightDescription: 'The contracting client, media outlet and agency each receive 1%. Cashback is credited transparently and remains valid for 90 days after it becomes available.',
    split: ['Contracting client: 1%', 'Media outlet: 1%', 'Agency: 1%'],
    ctaTitle: 'Request cashback',
    cta: 'Request my cashback',
  },
  es: {
    eyebrow: 'Programa de Cashback Ummix Ads',
    heroTitle: 'Anúnciate y gana',
    heroAccent: 'hasta un 3% de cashback',
    heroDescription: 'Con cada contrato cerrado, Ummix Ads devuelve parte del valor a quienes participaron en la negociación. Regístrate y empieza a recibirlo.',
    platformShort: 'Acceder a la plataforma',
    platformLong: 'Acceder a la plataforma de cashback',
    howItWorks: 'Cómo funciona',
    eligibility: 'Elegibilidad',
    eligibilityTitle: '¿Quién puede recibir cashback?',
    eligibilityDescription: 'Cada participante elegible recibe un 1% de cashback, hasta un total de 3% distribuidos por contrato.',
    participants: [
      ['Contratante', 'El anunciante que contrata directamente la campaña.'],
      ['Medio', 'El medio que firma el PI, cuando corresponde a la negociación.'],
      ['Agencia / Agencia digital / Gestor de tráfico', 'El gestor o intermediario responsable del contrato.'],
    ],
    eachCashback: '1% de cashback',
    rulesTitle: 'Reglas para recibir el cashback',
    rules: [
      'El contrato debe estar pagado íntegramente hasta la fecha de vencimiento.',
      'El participante debe tener un registro activo en la Plataforma de Cashback de Ummix Ads.',
      'El crédito debe solicitarse directamente en la Plataforma de Cashback de Ummix Ads.',
    ],
    howKicker: 'Cómo funciona',
    howTitle: 'Del registro al canje, en cinco pasos.',
    howDescription: 'El proceso es simple y transparente. Sigue cada etapa.',
    stepLabel: 'PASO',
    steps: [
      ['Registro', 'El participante se registra en la Plataforma de Cashback de Ummix Ads.'],
      ['Pago del contrato', 'Una vez confirmado el pago dentro del plazo, el cashback pasa a ser elegible.'],
      ['Solicitud', 'El participante solicita el crédito directamente en la plataforma e informa los datos del contrato.'],
      ['Crédito disponible', 'Después de validar la información, el importe se acredita en la cuenta del participante dentro de la plataforma.'],
      ['Uso del beneficio', 'El crédito puede utilizarse para canjear vouchers, cambiarlo por productos de partners o retirarlo en efectivo.'],
    ],
    highlightTitle: 'Hasta un 3% distribuido por contrato.',
    highlightDescription: 'El contratante, el medio y la agencia reciben un 1% cada uno. El cashback se acredita de forma transparente y es válido durante 90 días después de estar disponible.',
    split: ['Contratante: 1%', 'Medio: 1%', 'Agencia: 1%'],
    ctaTitle: 'Solicitar cashback',
    cta: 'Solicitar mi cashback',
  },
}
