export const HOME_COPY = {
  pt: {
    hero: {
      awardsCta: 'Prêmios e Certificações',
      flowLabels: ['PLANEJAR', 'COMPRAR', 'EXECUTAR', 'AUDITAR', 'RESULTADOS'],
      flowKicker: 'Da contratação à prestação de contas',
      flowTitle: 'Uma operação única e integrada.',
      flowDescription: 'Método Ummix® de Gestão de Campanhas: planejamento, negociação, execução, auditoria e resultados.',
      headingLineOne: 'MÍDIA',
      headingAccentOne: 'OFF',
      headingLineTwo: 'INTELIGÊNCIA',
      headingAccentTwo: 'DIGITAL',
      description: 'Você escolhe o público, a região e o investimento. A Ummix seleciona os veículos de mídia e os horários para a sua campanha.',
      primaryCta: 'Conhecer o Método Ummix',
      secondaryCta: 'Quero anunciar',
      stats: ['Veículos parceiros', 'Etapas estratégicas', 'Atividades operacionais'],
    },
    clientView: {
      kicker: 'O que o cliente vê',
      titleAccent: 'Simples',
      titleRest: 'para quem contrata.',
      description: 'Toda a complexidade da mídia off, embrulhada em três entregáveis claros.',
      cards: ['Uma única campanha', 'Um único contrato', 'Um único relatório'],
    },
    segmentations: {
      kicker: 'A precisão do digital, na mídia OFF',
      title: 'Segmentações',
      titleAccent: 'disponíveis',
      description: 'Escolha o público certo. Atinja exatamente quem importa para sua campanha.',
      tabLabel: 'Tipos de segmentação',
      tabs: {
        demografica: { label: 'Demográfica', attributes: ['Idade', 'Sexo', 'Renda familiar', 'Escolaridade', 'Profissão', 'Estado civil', 'Tamanho da família', 'Faixa etária'] },
        geografica: { label: 'Geográfica', attributes: ['País', 'Região', 'Estado', 'Cidade', 'Bairro', 'CEP', 'Raio de alcance', 'Pontos de interesse'] },
        comportamental: { label: 'Comportamental', attributes: ['Interesses', 'Hábitos de consumo', 'Estilo de vida', 'Engajamento digital', 'Histórico de compras', 'Padrão de uso', 'Eventos sazonais', 'Perfil socioemocional'] },
      },
      footer: 'Cruzamos múltiplas dimensões para atingir o público exato da sua campanha.',
    },
    backstage: {
      title: 'O que a Ummix faz',
      accent: 'nos bastidores',
      stats: ['Etapas estratégicas', 'Atividades operacionais', 'Validações'],
      statsValues: ['10', '+50', 'Múltiplas'],
      labels: ['Negociação Inteligente', 'Operação Especializada', 'Monitoramento em Tempo Real', 'Auditoria Independente', 'Gestão Financeira', 'Relatórios e Resultados'],
      campaign: 'Sua Campanha',
      closing: 'A Ummix simplifica o',
      closingAccent: 'complexo',
      closingRest: 'e centraliza tudo para você.',
    },
    method: {
      kicker: 'O método',
      title: 'Método',
      description: '10 etapas, do briefing ao encerramento. Cada uma é uma promessa cumprida.',
      autoplay: 'Auto-play',
      previous: 'Etapa anterior',
      next: 'Próxima etapa',
      step: 'Etapa',
      of: 'de',
      goTo: 'Ir para etapa',
      steps: [
        ['Validação Estratégica', 'Conferência do contrato, investimentos, veículos e objetivos da campanha. Alinhamento total antes de qualquer execução.', 'Briefing · Contrato · KPIs'],
        ['Inteligência de Mídia', 'Mapeamento de veículos, análise de inventário e custo por CPM. A base estratégica que define onde sua mensagem terá mais impacto.', 'Inventário · CPM · Mix de mídia'],
        ['Negociação e Reserva', 'Negociação direta com veículos, reserva de espaços e garantia das melhores condições comerciais.', 'Veículos · Espaços · Condições'],
        ['Gestão Operacional', 'Emissão de PIs, distribuição de planejamentos e gestão de prazos. Cada detalhe operacional sob controle.', 'PIs · Planejamentos · Prazos'],
        ['Gestão de Materiais', 'Recebimento, conferência e aprovação de materiais. Produção sob demanda quando necessário.', 'Recebimento · Aprovação · Produção'],
        ['Monitoramento e Auditoria', 'Monitoramento em tempo real, auditoria das inserções e validação contínua das veiculações.', 'Tempo real · Auditoria · Validação'],
        ['Gestão Financeira', 'Controle financeiro, repasses, cashback e conciliações com parceiros. Total transparência no dinheiro.', 'Repasses · Cashback · Conciliação'],
        ['Governança e Controle', 'Gestão de contratos, acompanhamento por praça e indicadores de performance em todo o ecossistema.', 'Contratos · Praças · KPIs'],
        ['Relatórios e Resultados', 'Consolidação de dados, auditoria final e entrega de relatórios com evidências comprobatórias.', 'Dados · Evidências · Insights'],
        ['Encerramento e Benefícios', 'Conferência final, liberação de cashback/BV e encerramento estratégico da campanha.', 'Conferência · Cashback · BV'],
      ],
    },
    eliminates: {
      kicker: 'O que isso elimina',
      title: 'Menos complexidade.',
      accent: 'Mais tempo',
      titleRest: 'para o que importa.',
      description: 'A Ummix absorve toda a operação da mídia off para que você foque em estratégia e resultado.',
      items: ['Negociar com dezenas de veículos', 'Controlar entregas e prazos', 'Conferir veiculações', 'Gerenciar pagamentos', 'Consolidar dados e relatórios'],
    },
    deliverables: {
      kicker: 'O que a Ummix realmente entrega',
      title: 'Uma operação completa,',
      accent: 'um único objetivo.',
      items: [
        ['Compra inteligente', 'Melhor eficiência para o investimento.', 'Veículos · Espaços · Condições'],
        ['Gestão operacional', 'Execução precisa e centralizada.', 'PIs · Planejamentos · Prazos'],
        ['Auditoria independente', 'Transparência e segurança na entrega.', 'Tempo real · Auditoria · Validação'],
        ['Prestação de contas', 'Relatórios completos e confiáveis.', 'Dados · Evidências · Insights'],
      ],
    },
    forWhom: {
      kicker: 'Para quem é',
      title: 'Um ecossistema conectado.',
      accent: 'Resultados reais.',
      audiences: [
        ['Anunciantes', 'Mais eficiência, transparência e resultados para sua marca.'],
        ['Agências', 'Um parceiro estratégico que cuida de toda a operação de mídia.'],
        ['Veículos', 'Relacionamento profissional, claro e de longo prazo.'],
        ['Poder Público', 'Comunicação institucional planejada para cada região e público.'],
        ['Bandas, cantores, duplas e escritórios musicais', 'Divulgação de lançamentos, shows e projetos para públicos locais.'],
        ['Agências Digitais e Gestores de Tráfego', 'Mídia offline para complementar estratégias e campanhas digitais.'],
      ],
    },
    cashbackSection: {
      kicker: 'Cashback Ummix',
      title: 'Campanhas orientadas por audiência real e inteligência de dados.',
      description: 'Até 3% de cashback é apenas um dos benefícios.',
      cta: 'Conhecer o cashback',
    },
    contact: {
      button: 'Falar com a Ummix',
      close: 'Fechar formulário',
      title: 'Fale com a Ummix',
      description: 'Conte um pouco sobre o que você precisa. Nossa equipe entra em contato.',
      name: 'Nome*',
      phone: 'Telefone*',
      email: 'E-mail*',
      message: 'Mensagem',
      error: 'Não foi possível enviar agora. Tente novamente em alguns instantes.',
      submitting: 'Enviando...',
      submit: 'Enviar mensagem',
      successTitle: 'Mensagem enviada.',
      successDescription: 'Obrigado pelo contato. Em breve, falaremos com você.',
      subject: 'Novo contato pelo site da Ummix',
    },
    partners: {
      vehicles: 'Veículos com histórico de mídia gerenciada pela Ummix',
      clients: 'Anunciantes e parceiros que confiam na Ummix',
    },
  },
  en: {
    hero: {
      awardsCta: 'Awards & Certifications',
      flowLabels: ['PLAN', 'BUY', 'EXECUTE', 'AUDIT', 'RESULTS'],
      flowKicker: 'From contracting to accountability',
      flowTitle: 'One integrated operation.',
      flowDescription: 'The Ummix® Campaign Management Method: planning, negotiation, execution, auditing and results.',
      headingLineOne: 'OFFLINE',
      headingAccentOne: 'MEDIA',
      headingLineTwo: 'DIGITAL',
      headingAccentTwo: 'INTELLIGENCE',
      description: 'You choose the audience, region and investment. Ummix selects the media outlets and time slots for your campaign.',
      primaryCta: 'Discover the Ummix Method',
      secondaryCta: 'I want to advertise',
      stats: ['Partner media outlets', 'Strategic stages', 'Operational activities'],
    },
    clientView: {
      kicker: 'What the client sees',
      titleAccent: 'Simple',
      titleRest: 'for the people who hire us.',
      description: 'All the complexity of offline media, wrapped into three clear deliverables.',
      cards: ['One campaign', 'One contract', 'One report'],
    },
    segmentations: {
      kicker: 'Digital precision for offline media',
      title: 'Available',
      titleAccent: 'targeting',
      description: 'Choose the right audience. Reach exactly who matters to your campaign.',
      tabLabel: 'Targeting types',
      tabs: {
        demografica: { label: 'Demographic', attributes: ['Age', 'Gender', 'Household income', 'Education', 'Occupation', 'Marital status', 'Family size', 'Age range'] },
        geografica: { label: 'Geographic', attributes: ['Country', 'Region', 'State', 'City', 'Neighborhood', 'ZIP code', 'Reach radius', 'Points of interest'] },
        comportamental: { label: 'Behavioral', attributes: ['Interests', 'Consumption habits', 'Lifestyle', 'Digital engagement', 'Purchase history', 'Usage patterns', 'Seasonal events', 'Socio-emotional profile'] },
      },
      footer: 'We cross multiple dimensions to reach the exact audience for your campaign.',
    },
    backstage: {
      title: 'What Ummix does',
      accent: 'behind the scenes',
      stats: ['Strategic stages', 'Operational activities', 'Validations'],
      statsValues: ['10', '+50', 'Multiple'],
      labels: ['Smart Negotiation', 'Specialized Operations', 'Real-Time Monitoring', 'Independent Audit', 'Financial Management', 'Reports & Results'],
      campaign: 'Your Campaign',
      closing: 'Ummix simplifies the',
      closingAccent: 'complex',
      closingRest: 'and centralizes everything for you.',
    },
    method: {
      kicker: 'The method',
      title: 'The',
      description: '10 stages, from briefing to closeout. Each one is a promise delivered.',
      autoplay: 'Auto-play',
      previous: 'Previous stage',
      next: 'Next stage',
      step: 'Stage',
      of: 'of',
      goTo: 'Go to stage',
      steps: [
        ['Strategic Validation', 'Review of the contract, investment, media outlets and campaign objectives. Full alignment before any execution.', 'Briefing · Contract · KPIs'],
        ['Media Intelligence', 'Media mapping, inventory analysis and CPM cost. The strategic foundation that defines where your message will have the most impact.', 'Inventory · CPM · Media mix'],
        ['Negotiation & Reservation', 'Direct negotiation with media outlets, space reservations and the best commercial conditions.', 'Media · Space · Conditions'],
        ['Operational Management', 'PI issuance, plan distribution and deadline management. Every operational detail under control.', 'PIs · Plans · Deadlines'],
        ['Materials Management', 'Material receipt, review and approval. On-demand production whenever needed.', 'Receipt · Approval · Production'],
        ['Monitoring & Audit', 'Real-time monitoring, insertion auditing and continuous validation of placements.', 'Real time · Audit · Validation'],
        ['Financial Management', 'Financial control, transfers, cashback and partner reconciliations. Complete financial transparency.', 'Transfers · Cashback · Reconciliation'],
        ['Governance & Control', 'Contract management, market-by-market tracking and performance indicators across the ecosystem.', 'Contracts · Markets · KPIs'],
        ['Reports & Results', 'Data consolidation, final audit and reports delivered with supporting evidence.', 'Data · Evidence · Insights'],
        ['Closeout & Benefits', 'Final review, cashback/BV release and strategic campaign closeout.', 'Review · Cashback · BV'],
      ],
    },
    eliminates: {
      kicker: 'What this eliminates',
      title: 'Less complexity.',
      accent: 'More time',
      titleRest: 'for what matters.',
      description: 'Ummix absorbs the entire offline media operation so you can focus on strategy and results.',
      items: ['Negotiating with dozens of media outlets', 'Tracking deliveries and deadlines', 'Checking placements', 'Managing payments', 'Consolidating data and reports'],
    },
    deliverables: {
      kicker: 'What Ummix really delivers',
      title: 'A complete operation,',
      accent: 'one single goal.',
      items: [
        ['Smart buying', 'Better efficiency for your investment.', 'Media · Space · Conditions'],
        ['Operational management', 'Precise, centralized execution.', 'PIs · Plans · Deadlines'],
        ['Independent audit', 'Transparency and delivery security.', 'Real time · Audit · Validation'],
        ['Accountability', 'Complete, reliable reports.', 'Data · Evidence · Insights'],
      ],
    },
    forWhom: {
      kicker: 'Who it is for',
      title: 'A connected ecosystem.',
      accent: 'Real results.',
      audiences: [
        ['Advertisers', 'More efficiency, transparency and results for your brand.'],
        ['Agencies', 'A strategic partner that takes care of your entire media operation.'],
        ['Media outlets', 'Professional, clear and long-term relationships.'],
        ['Public sector', 'Institutional communication planned for each region and audience.'],
        ['Bands, singers, duos and music offices', 'Promotion for releases, shows and projects aimed at local audiences.'],
        ['Digital agencies and media buyers', 'Offline media to complement digital strategies and campaigns.'],
      ],
    },
    cashbackSection: {
      kicker: 'Ummix Cashback',
      title: 'Campaigns guided by real audiences and data intelligence.',
      description: 'Up to 3% cashback is only one of the benefits.',
      cta: 'Discover cashback',
    },
    contact: {
      button: 'Talk to Ummix',
      close: 'Close form',
      title: 'Talk to Ummix',
      description: 'Tell us a little about what you need. Our team will get in touch.',
      name: 'Name*',
      phone: 'Phone*',
      email: 'Email*',
      message: 'Message',
      error: 'We could not send this right now. Please try again in a few moments.',
      submitting: 'Sending...',
      submit: 'Send message',
      successTitle: 'Message sent.',
      successDescription: 'Thank you for reaching out. We will talk to you soon.',
      subject: 'New contact from the Ummix website',
    },
    partners: {
      vehicles: 'Media outlets with a history of campaigns managed by Ummix',
      clients: 'Advertisers and partners who trust Ummix',
    },
  },
  es: {
    hero: {
      awardsCta: 'Premios y certificaciones',
      flowLabels: ['PLANIFICAR', 'COMPRAR', 'EJECUTAR', 'AUDITAR', 'RESULTADOS'],
      flowKicker: 'De la contratación a la rendición de cuentas',
      flowTitle: 'Una operación única e integrada.',
      flowDescription: 'Método Ummix® de Gestión de Campañas: planificación, negociación, ejecución, auditoría y resultados.',
      headingLineOne: 'MEDIOS',
      headingAccentOne: 'OFFLINE',
      headingLineTwo: 'INTELIGENCIA',
      headingAccentTwo: 'DIGITAL',
      description: 'Tú eliges la audiencia, la región y la inversión. Ummix selecciona los medios y los horarios para tu campaña.',
      primaryCta: 'Conoce el Método Ummix',
      secondaryCta: 'Quiero anunciarme',
      stats: ['Medios asociados', 'Etapas estratégicas', 'Actividades operativas'],
    },
    clientView: {
      kicker: 'Lo que ve el cliente',
      titleAccent: 'Simple',
      titleRest: 'para quien contrata.',
      description: 'Toda la complejidad de los medios offline, resumida en tres entregables claros.',
      cards: ['Una sola campaña', 'Un solo contrato', 'Un solo informe'],
    },
    segmentations: {
      kicker: 'La precisión de lo digital, en los medios OFF',
      title: 'Segmentaciones',
      titleAccent: 'disponibles',
      description: 'Elige la audiencia adecuada. Llega exactamente a quienes importan para tu campaña.',
      tabLabel: 'Tipos de segmentación',
      tabs: {
        demografica: { label: 'Demográfica', attributes: ['Edad', 'Sexo', 'Ingresos del hogar', 'Nivel educativo', 'Profesión', 'Estado civil', 'Tamaño de la familia', 'Rango de edad'] },
        geografica: { label: 'Geográfica', attributes: ['País', 'Región', 'Estado', 'Ciudad', 'Barrio', 'Código postal', 'Radio de alcance', 'Puntos de interés'] },
        comportamental: { label: 'Conductual', attributes: ['Intereses', 'Hábitos de consumo', 'Estilo de vida', 'Interacción digital', 'Historial de compras', 'Patrones de uso', 'Eventos estacionales', 'Perfil socioemocional'] },
      },
      footer: 'Cruzamos múltiples dimensiones para llegar a la audiencia exacta de tu campaña.',
    },
    backstage: {
      title: 'Lo que hace Ummix',
      accent: 'entre bastidores',
      stats: ['Etapas estratégicas', 'Actividades operativas', 'Validaciones'],
      statsValues: ['10', '+50', 'Múltiples'],
      labels: ['Negociación inteligente', 'Operación especializada', 'Monitoreo en tiempo real', 'Auditoría independiente', 'Gestión financiera', 'Informes y resultados'],
      campaign: 'Tu campaña',
      closing: 'Ummix simplifica lo',
      closingAccent: 'complejo',
      closingRest: 'y centraliza todo para ti.',
    },
    method: {
      kicker: 'El método',
      title: 'Método',
      description: '10 etapas, desde el briefing hasta el cierre. Cada una es una promesa cumplida.',
      autoplay: 'Reproducción automática',
      previous: 'Etapa anterior',
      next: 'Siguiente etapa',
      step: 'Etapa',
      of: 'de',
      goTo: 'Ir a la etapa',
      steps: [
        ['Validación estratégica', 'Revisión del contrato, la inversión, los medios y los objetivos de la campaña. Alineación total antes de cualquier ejecución.', 'Briefing · Contrato · KPIs'],
        ['Inteligencia de medios', 'Mapeo de medios, análisis de inventario y costo por CPM. La base estratégica que define dónde tu mensaje tendrá mayor impacto.', 'Inventario · CPM · Mix de medios'],
        ['Negociación y reserva', 'Negociación directa con los medios, reserva de espacios y garantía de las mejores condiciones comerciales.', 'Medios · Espacios · Condiciones'],
        ['Gestión operativa', 'Emisión de PIs, distribución de planes y gestión de plazos. Cada detalle operativo bajo control.', 'PIs · Planes · Plazos'],
        ['Gestión de materiales', 'Recepción, revisión y aprobación de materiales. Producción bajo demanda cuando sea necesario.', 'Recepción · Aprobación · Producción'],
        ['Monitoreo y auditoría', 'Monitoreo en tiempo real, auditoría de las inserciones y validación continua de las publicaciones.', 'Tiempo real · Auditoría · Validación'],
        ['Gestión financiera', 'Control financiero, transferencias, cashback y conciliaciones con partners. Transparencia total del dinero.', 'Transferencias · Cashback · Conciliación'],
        ['Gobernanza y control', 'Gestión de contratos, seguimiento por mercado e indicadores de rendimiento en todo el ecosistema.', 'Contratos · Mercados · KPIs'],
        ['Informes y resultados', 'Consolidación de datos, auditoría final y entrega de informes con evidencias comprobatorias.', 'Datos · Evidencias · Insights'],
        ['Cierre y beneficios', 'Revisión final, liberación de cashback/BV y cierre estratégico de la campaña.', 'Revisión · Cashback · BV'],
      ],
    },
    eliminates: {
      kicker: 'Lo que esto elimina',
      title: 'Menos complejidad.',
      accent: 'Más tiempo',
      titleRest: 'para lo que importa.',
      description: 'Ummix absorbe toda la operación de medios offline para que te enfoques en la estrategia y los resultados.',
      items: ['Negociar con decenas de medios', 'Controlar entregas y plazos', 'Comprobar publicaciones', 'Gestionar pagos', 'Consolidar datos e informes'],
    },
    deliverables: {
      kicker: 'Lo que Ummix realmente entrega',
      title: 'Una operación completa,',
      accent: 'un solo objetivo.',
      items: [
        ['Compra inteligente', 'Mayor eficiencia para tu inversión.', 'Medios · Espacios · Condiciones'],
        ['Gestión operativa', 'Ejecución precisa y centralizada.', 'PIs · Planes · Plazos'],
        ['Auditoría independiente', 'Transparencia y seguridad en la entrega.', 'Tiempo real · Auditoría · Validación'],
        ['Rendición de cuentas', 'Informes completos y confiables.', 'Datos · Evidencias · Insights'],
      ],
    },
    forWhom: {
      kicker: 'Para quién es',
      title: 'Un ecosistema conectado.',
      accent: 'Resultados reales.',
      audiences: [
        ['Anunciantes', 'Más eficiencia, transparencia y resultados para tu marca.'],
        ['Agencias', 'Un partner estratégico que se ocupa de toda tu operación de medios.'],
        ['Medios', 'Una relación profesional, clara y de largo plazo.'],
        ['Sector público', 'Comunicación institucional planificada para cada región y audiencia.'],
        ['Bandas, cantantes, dúos y oficinas de música', 'Promoción de lanzamientos, shows y proyectos para audiencias locales.'],
        ['Agencias digitales y gestores de tráfico', 'Medios offline para complementar estrategias y campañas digitales.'],
      ],
    },
    cashbackSection: {
      kicker: 'Cashback Ummix',
      title: 'Campañas orientadas por audiencias reales e inteligencia de datos.',
      description: 'Hasta un 3% de cashback es solo uno de los beneficios.',
      cta: 'Conoce el cashback',
    },
    contact: {
      button: 'Hablar con Ummix',
      close: 'Cerrar formulario',
      title: 'Habla con Ummix',
      description: 'Cuéntanos un poco sobre lo que necesitas. Nuestro equipo se pondrá en contacto.',
      name: 'Nombre*',
      phone: 'Teléfono*',
      email: 'Correo electrónico*',
      message: 'Mensaje',
      error: 'No fue posible enviar el mensaje ahora. Inténtalo de nuevo en unos instantes.',
      submitting: 'Enviando...',
      submit: 'Enviar mensaje',
      successTitle: 'Mensaje enviado.',
      successDescription: 'Gracias por contactarnos. Hablaremos contigo pronto.',
      subject: 'Nuevo contacto desde el sitio web de Ummix',
    },
    partners: {
      vehicles: 'Medios con historial de campañas gestionadas por Ummix',
      clients: 'Anunciantes y partners que confían en Ummix',
    },
  },
}
