export const MONETIZE_COPY = {
  pt: {
    eyebrow: 'Nova frente Ummix Ads',
    heroTitle: 'Você já tem audiência no digital.',
    heroAccent: 'Agora ela também pode gerar receita.',
    heroDescription: 'Transforme seu streaming em uma nova fonte de receita com a Ummix. A Ummix assume o custo do seu streaming, conecta anunciantes à sua audiência digital e seu veículo participa da receita gerada pela publicidade.',
    heroNote: 'Áudio ou vídeo. Rádio ou TV.',
    heroCta: 'Quero monetizar minha audiência',
    visualAria: 'Painel visual mostrando um streaming ao vivo e um espaço de pré-roll antes do conteúdo.',
    visualStatus: 'NO AR',
    visualRoute: 'STREAM / 001',
    visualContent: 'SEU CONTEÚDO',
    visualTime: '00:00:27',
    visualFormatLabel: 'Formato',
    visualFormat: 'Áudio + vídeo',
    visualAudienceLabel: 'Audiência',
    visualAudience: 'Ativa agora',
    visualAd: 'PRÉ-ROLL',
    visualAdText: 'entra antes do conteúdo',
    proposalTitle: 'E se o seu streaming deixasse de ser um custo e começasse a gerar receita?',
    proposalIntro: 'Hoje, seu veículo investe para disponibilizar sua programação também no ambiente digital.',
    proposalBullets: ['Você produz o conteúdo.', 'Você conquista a audiência.', 'Você mantém o streaming.'],
    proposalBridge: 'A Ummix entra para mudar essa equação.',
    proposalDescription: 'Nós assumimos o custo do streaming e transformamos essa audiência em inventário publicitário. Com o pré-roll, anúncios podem ser entregues antes do acesso ao conteúdo. A Ummix comercializa esse inventário e o veículo participa da receita gerada.',
    proposalClosing: 'Menos custo. Mais receita. A mesma audiência.',
    proposalEquation: [
      ['Você mantém', 'a audiência'],
      ['A Ummix assume', 'o streaming'],
      ['Juntos criamos', 'inventário'],
    ],
    processTitle: 'Do streaming ao inventário, em cinco movimentos.',
    processDescription: 'Um modelo simples para transformar uma estrutura que já existe em uma oportunidade comercial para o seu veículo.',
    processCta: 'Quero cadastrar meu veículo',
    steps: [
      ['Cadastre seu veículo', 'Informe os dados básicos da operação.'],
      ['A Ummix entra em contato', 'Nossa equipe apresenta o modelo e avalia a integração.'],
      ['Estruturamos o streaming', 'A Ummix disponibiliza a infraestrutura necessária para áudio ou vídeo e assume esse custo dentro do projeto.'],
      ['Monetizamos a audiência', 'O inventário de pré-roll passa a fazer parte da oferta comercial da Ummix para anunciantes.'],
      ['O seu veículo ganha uma nova fonte de receita', 'Além de deixar de arcar com o custo do streaming, o veículo passa a ter uma nova possibilidade de faturamento com sua audiência digital.'],
    ],
    proofEyebrow: 'Prova Ummix',
    proofNumber: 'Quase R$ 1 milhão',
    proofUnit: 'em Valor Total de Negócios',
    proofTime: 'gerados em apenas 1 ano e 6 meses.',
    proofBody: 'Em pouco mais de um ano, a Ummix já movimentou quase R$ 1 milhão em negócios de mídia, conectando anunciantes a veículos de comunicação.',
    proofExpansion: 'Agora, estamos ampliando essa capacidade comercial para o digital.',
    proofPrinciples: [
      ['A audiência', 'é sua.'],
      ['A tecnologia e a comercialização', 'são com a Ummix.'],
      ['Uma nova receita', 'para você.'],
    ],
    formEyebrow: 'Cadastre seu veículo',
    formTitle: 'Quer transformar seu streaming em receita?',
    formDescription: 'Cadastre seu veículo para participar da nova frente de monetização digital da Ummix Ads. Nossa equipe entrará em contato para conhecer sua operação, apresentar o modelo e realizar a integração.',
    formSteps: [
      ['Conhecemos sua operação', 'Entendemos o veículo, sua presença digital e, se houver, o streaming atual.'],
      ['Apresentamos o modelo', 'Explicamos a integração, o pré-roll e a participação na receita.'],
      ['Avaliamos os próximos passos', 'Nossa equipe combina com você o caminho para colocar o projeto no ar.'],
    ],
    privacyNote: 'Seus dados serão usados pela Ummix Ads apenas para entrar em contato sobre esta oportunidade, conforme a Política de Privacidade.',
    sections: {
      vehicle: 'Dados do veículo',
      responsible: 'Responsável',
      streaming: 'Streaming atual (se houver)',
      consent: 'Consentimento',
    },
    fields: {
      vehicleName: 'Nome do veículo',
      vehicleType: 'Tipo de veículo',
      legalName: 'Razão Social',
      cnpj: 'CNPJ',
      city: 'Cidade',
      state: 'Estado',
      site: 'Site',
      responsibleName: 'Nome do responsável',
      role: 'Cargo / função',
      whatsapp: 'WhatsApp',
      email: 'E-mail',
      hasStreaming: 'Sua empresa disponibiliza sua programação por streaming atualmente?',
      streamType: 'Tipo de streaming',
      streamLink: 'Link atual do streaming',
      provider: 'Qual empresa fornece atualmente seu streaming?',
      monthlyCost: 'Qual é aproximadamente o custo mensal atual do streaming?',
      knowsAudience: 'Você conhece sua audiência digital mensal aproximada?',
      monthlyAudience: 'Audiência digital mensal aproximada',
    },
    placeholders: {
      vehicleName: 'Ex.: Rádio Horizonte',
      legalName: 'Nome registrado da empresa',
      cnpj: '00.000.000/0000-00',
      city: 'Sua cidade',
      site: 'seusite.com.br',
      responsibleName: 'Nome completo',
      role: 'Ex.: Diretor comercial',
      whatsapp: '(00) 00000-0000',
      email: 'voce@seuveiculo.com.br',
      streamLink: 'https://...',
      provider: 'Se souber, informe o fornecedor',
      monthlyAudience: 'Ex.: 25000',
    },
    vehicleTypes: ['Rádio', 'TV', 'Outro'],
    streamTypes: ['Áudio', 'Vídeo', 'Áudio e vídeo'],
    states: [
      ['AC', 'Acre'], ['AL', 'Alagoas'], ['AP', 'Amapá'], ['AM', 'Amazonas'], ['BA', 'Bahia'],
      ['CE', 'Ceará'], ['DF', 'Distrito Federal'], ['ES', 'Espírito Santo'], ['GO', 'Goiás'],
      ['MA', 'Maranhão'], ['MT', 'Mato Grosso'], ['MS', 'Mato Grosso do Sul'], ['MG', 'Minas Gerais'],
      ['PA', 'Pará'], ['PB', 'Paraíba'], ['PR', 'Paraná'], ['PE', 'Pernambuco'], ['PI', 'Piauí'],
      ['RJ', 'Rio de Janeiro'], ['RN', 'Rio Grande do Norte'], ['RS', 'Rio Grande do Sul'], ['RO', 'Rondônia'],
      ['RR', 'Roraima'], ['SC', 'Santa Catarina'], ['SP', 'São Paulo'], ['SE', 'Sergipe'], ['TO', 'Tocantins'],
    ],
    costOptions: ['Até R$ 100', 'De R$ 101 a R$ 250', 'De R$ 251 a R$ 500', 'De R$ 501 a R$ 1.000', 'Acima de R$ 1.000', 'Não sei responder', 'Prefiro não informar'],
    yes: 'Sim',
    no: 'Não',
    statePlaceholder: 'Selecione o estado',
    chooseOption: 'Selecione uma opção',
    audienceHint: 'Esse dado ajuda a Ummix a entender o potencial da oportunidade.',
    consent: 'Autorizo a Ummix Ads a utilizar os dados fornecidos para entrar em contato comigo sobre esta oportunidade, conforme a Política de Privacidade.',
    submit: 'Quero monetizar meu streaming',
    submitting: 'Enviando cadastro...',
    error: 'Não foi possível enviar agora. Confira os dados e tente novamente em alguns instantes.',
    successTitle: 'Seu veículo está cadastrado.',
    successDescription: 'Recebemos suas informações. A equipe da Ummix entrará em contato para conhecer sua operação, apresentar o modelo de monetização e avaliar os próximos passos para integração.',
    successClosing: 'Seu streaming já entrega conteúdo. Agora queremos fazer ele entregar receita também.',
    backToTop: 'Voltar ao início',
    subject: 'Novo cadastro para monetização de streaming da Ummix Ads',
  },
  en: {
    eyebrow: 'New Ummix Ads initiative',
    heroTitle: 'You already have a digital audience.',
    heroAccent: 'Now it can generate revenue too.',
    heroDescription: 'Turn your streaming into a new revenue source with Ummix. We cover your streaming infrastructure, connect advertisers to your digital audience and share the revenue generated by advertising with your outlet.',
    heroNote: 'Audio or video. Radio or TV.',
    heroCta: 'I want to monetize my audience',
    visualAria: 'Visual panel showing a live stream and a pre-roll slot before the content.',
    visualStatus: 'ON AIR',
    visualRoute: 'STREAM / 001',
    visualContent: 'YOUR CONTENT',
    visualTime: '00:00:27',
    visualFormatLabel: 'Format',
    visualFormat: 'Audio + video',
    visualAudienceLabel: 'Audience',
    visualAudience: 'Active now',
    visualAd: 'PRE-ROLL',
    visualAdText: 'runs before the content',
    proposalTitle: 'What if your streaming stopped being a cost and started generating revenue?',
    proposalIntro: 'Today, your outlet invests to make its programming available in the digital environment.',
    proposalBullets: ['You produce the content.', 'You build the audience.', 'You maintain the streaming.'],
    proposalBridge: 'Ummix enters to change that equation.',
    proposalDescription: 'We cover the cost of streaming and turn that audience into advertising inventory. With pre-roll, ads can be delivered before access to the content. Ummix sells that inventory and your outlet participates in the revenue generated.',
    proposalClosing: 'Less cost. More revenue. The same audience.',
    proposalEquation: [
      ['You keep', 'the audience'],
      ['Ummix covers', 'the streaming'],
      ['Together we create', 'inventory'],
    ],
    processTitle: 'From streaming to inventory, in five moves.',
    processDescription: 'A simple model that turns an existing structure into a commercial opportunity for your outlet.',
    processCta: 'I want to register my outlet',
    steps: [
      ['Register your outlet', 'Share the basic details of your operation.'],
      ['Ummix gets in touch', 'Our team presents the model and assesses the integration.'],
      ['We structure the streaming', 'Ummix provides the infrastructure required for audio or video and covers that cost within the project.'],
      ['We monetize the audience', 'The pre-roll inventory becomes part of Ummix’s commercial offer to advertisers.'],
      ['Your outlet gains a new revenue source', 'Along with no longer carrying the streaming cost, your outlet gains a new revenue opportunity from its digital audience.'],
    ],
    proofEyebrow: 'Ummix proof',
    proofNumber: 'Nearly R$ 1 million',
    proofUnit: 'in Total Business Value',
    proofTime: 'generated in just 1 year and 6 months.',
    proofBody: 'In just over a year, Ummix has already moved nearly R$ 1 million in media business, connecting advertisers with media outlets.',
    proofExpansion: 'Now, we are extending that commercial capability to digital.',
    proofPrinciples: [
      ['The audience', 'is yours.'],
      ['Technology and sales', 'are Ummix’s.'],
      ['A new revenue source', 'for you.'],
    ],
    formEyebrow: 'Register your outlet',
    formTitle: 'Ready to turn your streaming into revenue?',
    formDescription: 'Register your outlet to join Ummix Ads’ new digital monetization initiative. Our team will learn about your operation, present the model and assess the integration.',
    formSteps: [
      ['We learn about your operation', 'We understand the outlet, its digital presence and, if applicable, its current streaming.'],
      ['We present the model', 'We explain the integration, pre-roll and revenue share.'],
      ['We assess next steps', 'Our team agrees with you on the path to bring the project live.'],
    ],
    privacyNote: 'Your data will be used by Ummix Ads only to contact you about this opportunity, according to our Privacy Policy.',
    sections: {
      vehicle: 'Outlet details',
      responsible: 'Contact person',
      streaming: 'Current streaming (if any)',
      consent: 'Consent',
    },
    fields: {
      vehicleName: 'Outlet name',
      vehicleType: 'Outlet type',
      legalName: 'Legal name',
      cnpj: 'CNPJ / tax ID',
      city: 'City',
      state: 'State',
      site: 'Website',
      responsibleName: 'Contact name',
      role: 'Role / position',
      whatsapp: 'WhatsApp',
      email: 'Email',
      hasStreaming: 'Does your company currently offer streaming?',
      streamType: 'Streaming type',
      streamLink: 'Current streaming link',
      provider: 'Which company currently provides your streaming?',
      monthlyCost: 'What is the approximate current monthly streaming cost?',
      knowsAudience: 'Do you know your approximate monthly digital audience?',
      monthlyAudience: 'Approximate monthly digital audience',
    },
    placeholders: {
      vehicleName: 'E.g. Horizon Radio',
      legalName: 'Registered company name',
      cnpj: '00.000.000/0000-00',
      city: 'Your city',
      site: 'yourwebsite.com',
      responsibleName: 'Full name',
      role: 'E.g. Commercial director',
      whatsapp: '(00) 00000-0000',
      email: 'you@youroutlet.com',
      streamLink: 'https://...',
      provider: 'If you know it, share the provider',
      monthlyAudience: 'E.g. 25000',
    },
    vehicleTypes: ['Radio', 'TV', 'Other'],
    streamTypes: ['Audio', 'Video', 'Audio and video'],
    states: [
      ['AC', 'Acre'], ['AL', 'Alagoas'], ['AP', 'Amapá'], ['AM', 'Amazonas'], ['BA', 'Bahia'],
      ['CE', 'Ceará'], ['DF', 'Distrito Federal'], ['ES', 'Espírito Santo'], ['GO', 'Goiás'],
      ['MA', 'Maranhão'], ['MT', 'Mato Grosso'], ['MS', 'Mato Grosso do Sul'], ['MG', 'Minas Gerais'],
      ['PA', 'Pará'], ['PB', 'Paraíba'], ['PR', 'Paraná'], ['PE', 'Pernambuco'], ['PI', 'Piauí'],
      ['RJ', 'Rio de Janeiro'], ['RN', 'Rio Grande do Norte'], ['RS', 'Rio Grande do Sul'], ['RO', 'Rondônia'],
      ['RR', 'Roraima'], ['SC', 'Santa Catarina'], ['SP', 'São Paulo'], ['SE', 'Sergipe'], ['TO', 'Tocantins'],
    ],
    costOptions: ['Up to R$ 100', 'R$ 101 to R$ 250', 'R$ 251 to R$ 500', 'R$ 501 to R$ 1,000', 'Over R$ 1,000', "I don't know", 'Prefer not to say'],
    yes: 'Yes',
    no: 'No',
    statePlaceholder: 'Select a state',
    chooseOption: 'Select an option',
    audienceHint: 'This helps Ummix understand the opportunity’s potential.',
    consent: 'I authorize Ummix Ads to use the information provided to contact me about this opportunity, according to the Privacy Policy.',
    submit: 'I want to monetize my streaming',
    submitting: 'Sending registration...',
    error: 'We could not send this right now. Check the information and try again in a few moments.',
    successTitle: 'Your outlet is registered.',
    successDescription: 'We received your information. The Ummix team will get in touch to learn about your operation, present the monetization model and assess the next integration steps.',
    successClosing: 'Your streaming already delivers content. Now we want it to deliver revenue too.',
    backToTop: 'Back to top',
    subject: 'New streaming monetization registration for Ummix Ads',
  },
  es: {
    eyebrow: 'Nueva iniciativa de Ummix Ads',
    heroTitle: 'Ya tienes una audiencia digital.',
    heroAccent: 'Ahora también puede generar ingresos.',
    heroDescription: 'Convierte tu streaming en una nueva fuente de ingresos con Ummix. Ummix asume el costo de tu streaming, conecta anunciantes con tu audiencia digital y tu medio participa de los ingresos generados por la publicidad.',
    heroNote: 'Audio o vídeo. Radio o televisión.',
    heroCta: 'Quiero monetizar mi audiencia',
    visualAria: 'Panel visual que muestra una transmisión en directo y un espacio de pre-roll antes del contenido.',
    visualStatus: 'EN EL AIRE',
    visualRoute: 'STREAM / 001',
    visualContent: 'TU CONTENIDO',
    visualTime: '00:00:27',
    visualFormatLabel: 'Formato',
    visualFormat: 'Audio + vídeo',
    visualAudienceLabel: 'Audiencia',
    visualAudience: 'Activa ahora',
    visualAd: 'PRE-ROLL',
    visualAdText: 'aparece antes del contenido',
    proposalTitle: '¿Y si tu streaming dejara de ser un costo y empezara a generar ingresos?',
    proposalIntro: 'Hoy, tu medio invierte para ofrecer su programación también en el entorno digital.',
    proposalBullets: ['Tú produces el contenido.', 'Tú construyes la audiencia.', 'Tú mantienes el streaming.'],
    proposalBridge: 'Ummix entra para cambiar esa ecuación.',
    proposalDescription: 'Asumimos el costo del streaming y convertimos esa audiencia en inventario publicitario. Con el pre-roll, los anuncios pueden aparecer antes de acceder al contenido. Ummix comercializa ese inventario y tu medio participa de los ingresos generados.',
    proposalClosing: 'Menos costos. Más ingresos. La misma audiencia.',
    proposalEquation: [
      ['Tú mantienes', 'la audiencia'],
      ['Ummix asume', 'el streaming'],
      ['Juntos creamos', 'inventario'],
    ],
    processTitle: 'Del streaming al inventario, en cinco movimientos.',
    processDescription: 'Un modelo simple para convertir una estructura que ya existe en una oportunidad comercial para tu medio.',
    processCta: 'Quiero registrar mi medio',
    steps: [
      ['Registra tu medio', 'Comparte los datos básicos de tu operación.'],
      ['Ummix se pone en contacto', 'Nuestro equipo presenta el modelo y evalúa la integración.'],
      ['Estructuramos el streaming', 'Ummix ofrece la infraestructura necesaria para audio o vídeo y asume ese costo dentro del proyecto.'],
      ['Monetizamos la audiencia', 'El inventario de pre-roll pasa a formar parte de la oferta comercial de Ummix para anunciantes.'],
      ['Tu medio obtiene una nueva fuente de ingresos', 'Además de dejar de asumir el costo del streaming, tu medio obtiene una nueva posibilidad de facturación a partir de su audiencia digital.'],
    ],
    proofEyebrow: 'Prueba Ummix',
    proofNumber: 'Casi R$ 1 millón',
    proofUnit: 'en Valor Total de Negocios',
    proofTime: 'generado en solo 1 año y 6 meses.',
    proofBody: 'En poco más de un año, Ummix ya ha movilizado casi R$ 1 millón en negocios de medios, conectando anunciantes con medios de comunicación.',
    proofExpansion: 'Ahora ampliamos esa capacidad comercial al entorno digital.',
    proofPrinciples: [
      ['La audiencia', 'es tuya.'],
      ['La tecnología y la comercialización', 'son de Ummix.'],
      ['Una nueva fuente de ingresos', 'para ti.'],
    ],
    formEyebrow: 'Registra tu medio',
    formTitle: '¿Quieres convertir tu streaming en ingresos?',
    formDescription: 'Registra tu medio para participar en la nueva iniciativa de monetización digital de Ummix Ads. Nuestro equipo se pondrá en contacto para conocer tu operación, presentarte el modelo y realizar la integración.',
    formSteps: [
      ['Conocemos tu operación', 'Entendemos el medio, su presencia digital y, si existe, el streaming actual.'],
      ['Presentamos el modelo', 'Explicamos la integración, el pre-roll y la participación en los ingresos.'],
      ['Evaluamos los siguientes pasos', 'Nuestro equipo acuerda contigo el camino para poner el proyecto en marcha.'],
    ],
    privacyNote: 'Ummix Ads utilizará tus datos únicamente para contactarte sobre esta oportunidad, de acuerdo con la Política de Privacidad.',
    sections: {
      vehicle: 'Datos del medio',
      responsible: 'Responsable',
      streaming: 'Streaming actual (si existe)',
      consent: 'Consentimiento',
    },
    fields: {
      vehicleName: 'Nombre del medio',
      vehicleType: 'Tipo de medio',
      legalName: 'Razón social',
      cnpj: 'CNPJ / identificación fiscal',
      city: 'Ciudad',
      state: 'Estado',
      site: 'Sitio web',
      responsibleName: 'Nombre del responsable',
      role: 'Cargo / función',
      whatsapp: 'WhatsApp',
      email: 'Correo electrónico',
      hasStreaming: '¿Tu empresa ofrece actualmente su programación por streaming?',
      streamType: 'Tipo de streaming',
      streamLink: 'Enlace actual del streaming',
      provider: '¿Qué empresa proporciona actualmente tu streaming?',
      monthlyCost: '¿Cuál es aproximadamente el costo mensual actual del streaming?',
      knowsAudience: '¿Conoces aproximadamente tu audiencia digital mensual?',
      monthlyAudience: 'Audiencia digital mensual aproximada',
    },
    placeholders: {
      vehicleName: 'Ej.: Radio Horizonte',
      legalName: 'Nombre registrado de la empresa',
      cnpj: '00.000.000/0000-00',
      city: 'Tu ciudad',
      site: 'tusitio.com.br',
      responsibleName: 'Nombre completo',
      role: 'Ej.: Director comercial',
      whatsapp: '+55 (00) 00000-0000',
      email: 'tu@tumedio.com.br',
      streamLink: 'https://...',
      provider: 'Si lo sabes, indica el proveedor',
      monthlyAudience: 'Ej.: 25000',
    },
    vehicleTypes: ['Radio', 'TV', 'Otro'],
    streamTypes: ['Audio', 'Vídeo', 'Audio y vídeo'],
    states: [
      ['AC', 'Acre'], ['AL', 'Alagoas'], ['AP', 'Amapá'], ['AM', 'Amazonas'], ['BA', 'Bahía'],
      ['CE', 'Ceará'], ['DF', 'Distrito Federal'], ['ES', 'Espírito Santo'], ['GO', 'Goiás'],
      ['MA', 'Maranhão'], ['MT', 'Mato Grosso'], ['MS', 'Mato Grosso do Sul'], ['MG', 'Minas Gerais'],
      ['PA', 'Pará'], ['PB', 'Paraíba'], ['PR', 'Paraná'], ['PE', 'Pernambuco'], ['PI', 'Piauí'],
      ['RJ', 'Río de Janeiro'], ['RN', 'Río Grande do Norte'], ['RS', 'Río Grande do Sul'], ['RO', 'Rondônia'],
      ['RR', 'Roraima'], ['SC', 'Santa Catarina'], ['SP', 'São Paulo'], ['SE', 'Sergipe'], ['TO', 'Tocantins'],
    ],
    costOptions: ['Hasta R$ 100', 'De R$ 101 a R$ 250', 'De R$ 251 a R$ 500', 'De R$ 501 a R$ 1.000', 'Más de R$ 1.000', 'No sé responder', 'Prefiero no informar'],
    yes: 'Sí',
    no: 'No',
    statePlaceholder: 'Selecciona el estado',
    chooseOption: 'Selecciona una opción',
    audienceHint: 'Este dato ayuda a Ummix a entender el potencial de la oportunidad.',
    consent: 'Autorizo a Ummix Ads a utilizar los datos proporcionados para contactarme sobre esta oportunidad, de acuerdo con la Política de Privacidad.',
    submit: 'Quiero monetizar mi streaming',
    submitting: 'Enviando registro...',
    error: 'No fue posible enviar el formulario ahora. Comprueba los datos e inténtalo de nuevo en unos instantes.',
    successTitle: 'Tu medio está registrado.',
    successDescription: 'Recibimos tu información. El equipo de Ummix se pondrá en contacto para conocer tu operación, presentarte el modelo de monetización y evaluar los siguientes pasos de integración.',
    successClosing: 'Tu streaming ya entrega contenido. Ahora queremos que también genere ingresos.',
    backToTop: 'Volver al inicio',
    subject: 'Nuevo registro para monetización de streaming de Ummix Ads',
  },
}
