export const PARTNER_COPY = {
  pt: {
    eyebrow: 'Programa de Parcerias Ummix Ads',
    heroTitle: 'Tenha agora acesso à',
    heroAccent: 'mídia de massa orientada a dados',
    heroDescription: 'Some a estratégia da sua empresa à inteligência de veiculação da Ummix em rádio, TV e mídia exterior. Amplie suas entregas e crie uma nova fonte de receita para o seu negócio.',
    apply: 'Quero ser um Partner',
    meetPartners: 'Conheça nossos Partners',
    kpis: [
      ['+80 veículos', 'disponíveis para campanhas das empresas parceiras'],
      ['24,5%', 'de comissão sobre a mídia veiculada'],
      ['Suporte dedicado', 'planejamento e mensuração junto com você'],
    ],
    pathsKicker: 'Escolha seu caminho',
    pathsTitle: 'Duas formas de fazer parte do ecossistema Ummix.',
    pathsDescription: 'Amplie suas entregas como Partner ou encontre uma empresa que ajude a estruturar sua próxima campanha.',
    pathJoinEyebrow: 'Para agências e profissionais',
    pathJoinTitle: 'Seja um Partner',
    pathJoinDescription: 'Leve mídia offline orientada a dados para seus clientes e conte com o método e o suporte da Ummix.',
    pathJoinCta: 'Quero ser um Partner',
    pathFindEyebrow: 'Para anunciantes',
    pathFindTitle: 'Conheça nossos Partners',
    pathFindDescription: 'Veja empresas que já integram nosso programa e acesse seus canais para conversar sobre sua campanha.',
    pathFindCta: 'Ver Partners',
    processKicker: 'Seja um Partner',
    processTitle: 'Da candidatura à primeira campanha.',
    processDescription: 'Um processo simples e transparente, da candidatura à primeira campanha no ar.',
    process: [
      ['Candidatura', 'Você preenche o formulário de interesse e nosso time avalia o perfil da sua empresa.'],
      ['Onboarding', 'Apresentamos a plataforma, o método Ummix e as condições comerciais da parceria.'],
      ['Ativação', 'Sua empresa ganha acesso à base de veículos e começa a montar campanhas para os clientes.'],
      ['Crescimento', 'Você acompanha resultados em tempo real e amplia a operação com nosso suporte contínuo.'],
    ],
    partnersKicker: 'Conheça nossos Partners',
    partnersTitle: 'Empresas que já integram o ecossistema Ummix.',
    partnersDescription: 'Conheça empresas que já fazem parte do nosso programa e fale diretamente com elas para estruturar sua campanha.',
    partnerLabel: 'Partner Ummix',
    partnerContactLabel: 'Canais para falar com este Partner',
    partnerFallbackKicker: 'Precisa de orientação?',
    partnerFallbackTitle: 'A Ummix ajuda você a dar o próximo passo.',
    partnerFallbackDescription: 'Se você ainda não sabe com quem falar, conte o que sua campanha precisa. Nossa equipe orienta o contato mais adequado dentro da rede disponível.',
    partnerFallbackCta: 'Falar com a Ummix',
    partnerFallbackSubject: 'Quero encontrar um Partner para minha campanha',
    formTitle: 'Vamos construir essa parceria?',
    formDescription: 'Conte um pouco sobre a sua empresa. Nosso time entra em contato para apresentar o programa.',
    benefits: ['Acesso a mais de 80 veículos de mídia', '24,5% de comissão sobre a mídia veiculada', 'Planejamento e mensuração com nosso time'],
    fields: [
      ['Nome', 'Seu nome completo'],
      ['E-mail corporativo', 'voce@suaempresa.com.br'],
      ['Nome da empresa', 'Como sua empresa se chama'],
      ['Telefone / WhatsApp', '(00) 00000-0000'],
    ],
    error: 'Não foi possível enviar agora. Tente novamente em alguns instantes.',
    submitting: 'Enviando...',
    submit: 'Enviar candidatura',
    successTitle: 'Candidatura recebida!',
    successDescription: 'Nosso time de parcerias entra em contato em breve.',
    subject: 'Nova candidatura ao Programa de Parcerias da Ummix',
  },
  en: {
    eyebrow: 'Ummix Ads Partner Program',
    heroTitle: 'Get access to',
    heroAccent: 'data-driven mass media',
    heroDescription: 'Combine your company strategy with Ummix media intelligence across radio, TV and out-of-home. Expand your offering and create a new revenue stream for your business.',
    apply: 'Become a Partner',
    meetPartners: 'Meet our Partners',
    kpis: [
      ['80+ outlets', 'available for partner company campaigns'],
      ['24.5%', 'commission on media placements'],
      ['Dedicated support', 'planning and measurement alongside you'],
    ],
    pathsKicker: 'Choose your path',
    pathsTitle: 'Two ways to be part of the Ummix ecosystem.',
    pathsDescription: 'Expand your offering as a Partner or find a company to help shape your next campaign.',
    pathJoinEyebrow: 'For agencies and professionals',
    pathJoinTitle: 'Become a Partner',
    pathJoinDescription: 'Bring data-driven offline media to your clients with Ummix method and support behind you.',
    pathJoinCta: 'Become a Partner',
    pathFindEyebrow: 'For advertisers',
    pathFindTitle: 'Meet our Partners',
    pathFindDescription: 'Explore companies already in our program and use their channels to discuss your campaign.',
    pathFindCta: 'View Partners',
    processKicker: 'Become a Partner',
    processTitle: 'From application to your first campaign.',
    processDescription: 'A simple, transparent process from application to your first live campaign.',
    process: [
      ['Application', 'You complete the interest form and our team reviews your company profile.'],
      ['Onboarding', 'We present the platform, the Ummix method and the commercial terms of the partnership.'],
      ['Activation', 'Your company gets access to the media base and starts building campaigns for clients.'],
      ['Growth', 'You track results in real time and scale your operation with our ongoing support.'],
    ],
    partnersKicker: 'Meet our Partners',
    partnersTitle: 'Companies already part of the Ummix ecosystem.',
    partnersDescription: 'Meet companies already in our program and contact them directly to shape your campaign.',
    partnerLabel: 'Ummix Partner',
    partnerContactLabel: 'Contact channels for this Partner',
    partnerFallbackKicker: 'Need guidance?',
    partnerFallbackTitle: 'Ummix can help with your next step.',
    partnerFallbackDescription: 'If you are not sure who to contact, tell us what your campaign needs. Our team can guide you to the most suitable contact within the available network.',
    partnerFallbackCta: 'Talk to Ummix',
    partnerFallbackSubject: 'I want to find a Partner for my campaign',
    formTitle: 'Shall we build this partnership?',
    formDescription: 'Tell us a little about your company. Our team will get in touch to present the program.',
    benefits: ['Access to more than 80 media outlets', '24.5% commission on media placements', 'Planning and measurement with our team'],
    fields: [
      ['Name', 'Your full name'],
      ['Business email', 'you@yourcompany.com'],
      ['Company name', 'What is your company called'],
      ['Phone / WhatsApp', '+1 (000) 000-0000'],
    ],
    error: 'We could not send this right now. Please try again in a few moments.',
    submitting: 'Sending...',
    submit: 'Send application',
    successTitle: 'Application received!',
    successDescription: 'Our partnerships team will contact you soon.',
    subject: 'New application for the Ummix Partner Program',
  },
}
