export const PARTNER_COPY = {
  pt: {
    eyebrow: 'Programa de Parcerias Ummix Ads',
    heroTitle: 'Tenha agora acesso à',
    heroAccent: 'mídia de massa orientada a dados',
    heroDescription: 'Some a estratégia da sua empresa à inteligência de veiculação da Ummix em rádio, TV e mídia exterior. Amplie suas entregas e crie uma nova fonte de receita para o seu negócio.',
    apply: 'Quero ser partner',
    howItWorks: 'Como funciona',
    kpis: [
      ['+80 veículos', 'disponíveis para campanhas das empresas parceiras'],
      ['24,5%', 'de comissão sobre a mídia veiculada'],
      ['Suporte dedicado', 'planejamento e mensuração junto com você'],
    ],
    processKicker: 'Como virar parceiro',
    processTitle: 'Quatro passos para começar.',
    processDescription: 'Um processo simples e transparente, da candidatura à primeira campanha no ar.',
    process: [
      ['Candidatura', 'Você preenche o formulário de interesse e nosso time avalia o perfil da sua empresa.'],
      ['Onboarding', 'Apresentamos a plataforma, o método Ummix e as condições comerciais da parceria.'],
      ['Ativação', 'Sua empresa ganha acesso à base de veículos e começa a montar campanhas para os clientes.'],
      ['Crescimento', 'Você acompanha resultados em tempo real e amplia a operação com nosso suporte contínuo.'],
    ],
    partnersKicker: 'Partners Ummix',
    partnersTitle: 'Empresas que já operam com a Ummix.',
    partnersDescription: 'Conheça as empresas que já integram nosso programa de parcerias.',
    partnerLabel: 'Partner Ummix',
    formTitle: 'Vamos construir essa parceria?',
    formDescription: 'Conte um pouco sobre a sua empresa. Nosso time entra em contato para apresentar o programa.',
    benefits: ['Acesso a mais de 80 veículos de mídia', '24,5% de comissão sobre a mídia veiculada', 'Planejamento e mensuração com nosso time'],
    fields: [
      ['Nome', 'Seu nome completo'],
      ['E-mail corporativo', 'voce@suaempresa.com.br'],
      ['Nome da empresa', 'Como sua empresa se chama'],
      ['Telefone / WhatsApp', '(00) 00000-0000'],
    ],
    error: 'Não foi possível enviar agora. Tente novamente em alguns instantes.',
    submitting: 'Enviando...',
    submit: 'Enviar candidatura',
    successTitle: 'Candidatura recebida!',
    successDescription: 'Nosso time de parcerias entra em contato em breve.',
    subject: 'Nova candidatura ao Programa de Parcerias da Ummix',
  },
  en: {
    eyebrow: 'Ummix Ads Partner Program',
    heroTitle: 'Get access to',
    heroAccent: 'data-driven mass media',
    heroDescription: 'Combine your company strategy with Ummix media intelligence across radio, TV and out-of-home. Expand your offering and create a new revenue stream for your business.',
    apply: 'Become a partner',
    howItWorks: 'How it works',
    kpis: [
      ['80+ outlets', 'available for partner company campaigns'],
      ['24.5%', 'commission on media placements'],
      ['Dedicated support', 'planning and measurement alongside you'],
    ],
    processKicker: 'How to become a partner',
    processTitle: 'Four steps to get started.',
    processDescription: 'A simple, transparent process from application to your first live campaign.',
    process: [
      ['Application', 'You complete the interest form and our team reviews your company profile.'],
      ['Onboarding', 'We present the platform, the Ummix method and the commercial terms of the partnership.'],
      ['Activation', 'Your company gets access to the media base and starts building campaigns for clients.'],
      ['Growth', 'You track results in real time and scale your operation with our ongoing support.'],
    ],
    partnersKicker: 'Ummix Partners',
    partnersTitle: 'Companies already operating with Ummix.',
    partnersDescription: 'Meet the companies that are already part of our partner program.',
    partnerLabel: 'Ummix Partner',
    formTitle: 'Shall we build this partnership?',
    formDescription: 'Tell us a little about your company. Our team will get in touch to present the program.',
    benefits: ['Access to more than 80 media outlets', '24.5% commission on media placements', 'Planning and measurement with our team'],
    fields: [
      ['Name', 'Your full name'],
      ['Business email', 'you@yourcompany.com'],
      ['Company name', 'What is your company called'],
      ['Phone / WhatsApp', '+1 (000) 000-0000'],
    ],
    error: 'We could not send this right now. Please try again in a few moments.',
    submitting: 'Sending...',
    submit: 'Send application',
    successTitle: 'Application received!',
    successDescription: 'Our partnerships team will contact you soon.',
    subject: 'New application for the Ummix Partner Program',
  },
}
